version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dogopedia
      MYSQL_USER: dog_user
      MYSQL_PASSWORD: dog
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=dog_user
      - DATABASE_PASSWORD=dog
      - DATABASE_NAME=dogopedia
    depends_on:
      - db

volumes:
  db_data:
